import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { NextFont } from "next/dist/compiled/@next/font"
import { AntdRegistry } from "@ant-design/nextjs-registry"
import "./globals.css"
import Provider from "./provider"

const poppins: NextFont = Poppins({
  weight: "400",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Next Auth Handson",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <AntdRegistry>
        <body suppressHydrationWarning>
          <Provider>{children}</Provider>
        </body>
      </AntdRegistry>
    </html>
  )
}
